apiVersion: v1
kind: Secret

metadata:
  name: shopflow-secret
  namespace: shopflow

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root

  DB_USER: root
  DB_PASSWORD: root

  JWT_SECRET: Z+bqADXEvM1dl03DVsWm4uznbttNqZyFwjNs6OlkMDE=

  EMAIL_USER: ""
  EMAIL_PASS: ""
