apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mysql-init-scripts
    files:
      - ../mysql-init/01-create-databases.sql

generatorOptions:
  disableNameSuffixHash: true