apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: shopflow-mysql
  namespace: shopflow
  labels:
    app: shopflow
    component: mysql

spec:
  serviceName: mysql
  replicas: 1

  selector:
    matchLabels:
      app: shopflow
      component: mysql

  template:
    metadata:
      labels:
        app: shopflow
        component: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopflow-secret
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

        - name: mysql-init-script
          configMap:
            name: mysql-init-script
