apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-configMap
  namespace: shopflow
data:
  EMAIL_ENABLED: "false"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_FROM: "ShopFlow <noreply@shopflow.com>"