apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secret
  namespace: shopflow
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  JWT_SECRET: "NVazzNbQwRyuzwxPEa/AQ0v7YPdMW/Ddjs7y/mFqUS8="
  EMAIL_USER: ""
  EMAIL_PASS: ""