apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopflow

spec:
  type: ClusterIP

  selector:
    app: notification-service

  ports:
    - port: 8005
      targetPort: 8005