apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopflow

resources:
  - namespace.yaml

  - config/configmap.yaml
  - config/secret.yaml

  - storage/persistent-volume-claim.yaml

  - mysql/mysql-init-configmap.yaml
  - mysql/service.yaml
  - mysql/statefulset.yaml

  - auth-service/service.yaml
  - auth-service/deployment.yaml

  - product-service/service.yaml
  - product-service/deployment.yaml

  - order-service/service.yaml
  - order-service/deployment.yaml

  - payment-service/service.yaml
  - payment-service/deployment.yaml

  - notification-service/service.yaml
  - notification-service/deployment.yaml

  - api-gateway/service.yaml
  - api-gateway/deployment.yaml

  - frontend/service.yaml
  - frontend/deployment.yaml

  - admin-dashboard/service.yaml
  - admin-dashboard/deployment.yaml

  - ingress/ingress.yaml
