apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopflow.configMapName" . }}
  namespace: {{ include "shopflow.namespace" . }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  AUTH_SERVICE_PORT: {{ .Values.config.authServicePort | quote }}
  PRODUCT_SERVICE_PORT: {{ .Values.config.productServicePort | quote }}
  ORDER_SERVICE_PORT: {{ .Values.config.orderServicePort | quote }}
  PAYMENT_SERVICE_PORT: {{ .Values.config.paymentServicePort | quote }}
  NOTIFICATION_SERVICE_PORT: {{ .Values.config.notificationServicePort | quote }}
  API_GATEWAY_PORT: {{ .Values.config.apiGatewayPort | quote }}
  AUTH_DB_NAME: {{ .Values.config.authDbName | quote }}
  PRODUCT_DB_NAME: {{ .Values.config.productDbName | quote }}
  ORDER_DB_NAME: {{ .Values.config.orderDbName | quote }}
  PAYMENT_DB_NAME: {{ .Values.config.paymentDbName | quote }}
  NOTIFICATION_DB_NAME: {{ .Values.config.notificationDbName | quote }}
  AUTH_SERVICE_URL: {{ .Values.config.authServiceUrl | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.config.productServiceUrl | quote }}
  ORDER_SERVICE_URL: {{ .Values.config.orderServiceUrl | quote }}
  PAYMENT_SERVICE_URL: {{ .Values.config.paymentServiceUrl | quote }}
  NOTIFICATION_SERVICE_URL: {{ .Values.config.notificationServiceUrl | quote }}
  JWT_EXPIRY_HOURS: {{ .Values.config.jwtExpiryHours | quote }}
  PAYMENT_SUCCESS_RATE: {{ .Values.config.paymentSuccessRate | quote }}
  EMAIL_ENABLED: {{ .Values.config.emailEnabled | quote }}
  EMAIL_HOST: {{ .Values.config.emailHost | quote }}
  EMAIL_PORT: {{ .Values.config.emailPort | quote }}
  EMAIL_FROM: {{ .Values.config.emailFrom | quote }}
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}
