apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "shopflow.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "shopflow.name" . }}
    app.kubernetes.io/part-of: shopflow-project
