apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopflow.secretName" . }}
  namespace: {{ include "shopflow.namespace" . }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote }}
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  EMAIL_USER: {{ .Values.secret.emailUser | quote }}
  EMAIL_PASS: {{ .Values.secret.emailPass | quote }}
