apiVersion: v1
kind: Service

metadata:
  name: product-service
  namespace: shopflow
  labels:
    app: shopflow
    component: product-service

spec:
  selector:
    app: shopflow
    component: product-service

  ports:
    - port: 8002
      targetPort: 8002

  type: ClusterIP
