apiVersion: apps/v1
kind: Deployment

metadata:
  name: shopflow-payment-service
  namespace: shopflow
  labels:
    app: shopflow
    component: payment-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: shopflow
      component: payment-service

  template:
    metadata:
      labels:
        app: shopflow
        component: payment-service

    spec:
      containers:
        - name: payment-service
          image: harishgundimeda/shopflow-project-payment-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8004

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: DB_PORT

            - name: DB_NAME
              value: payment_db

            - name: PORT
              value: "8004"

            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8001"

            - name: ORDER_SERVICE_URL
              value: "http://order-service:8003"

            - name: PAYMENT_SUCCESS_RATE
              value: "0.95"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shopflow-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopflow-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 20
