apiVersion: v1
kind: Service

metadata:
  name: payment-service
  namespace: shopflow
  labels:
    app: shopflow
    component: payment-service

spec:
  selector:
    app: shopflow
    component: payment-service

  ports:
    - port: 8004
      targetPort: 8004

  type: ClusterIP
